### ISSUE TITLE
AttributeError: type object 'Solver' has no attribute 'requirements'

### ISSUE THREAD

**Issue by UR4NVS** [benchopt/benchopt#561] opened 2023-06-06 09:57 UTC
## How to reproduce the error
I got *AttributeError: type object 'Solver' has no attribute 'requirements'* when I tried to launch a benchmark with XGBClassifier solver without installing in my conda environnement the package xgboost.

## Fixing the error
To fix it, I added a variable called `requirements` in the file of the solver causing this error (i.e `xgboost.py`). This variable must contain a list with the name of the solver's conda package (in this case it'll be `requirements = ["py-xgboost"]`).

**Comment by mathurinm** [comment] 2023-06-06 11:05
Hi @UR4NVS, thanks for your feedback ! 
If the solver is not installed, you indeed need to tell benchopt which packages needs to be installed in order for the solver to work, by adding a `requirements` attribute as you did.
 
 However I am surprised that you got a bug, because if the solver is not installed it should be skipped. Can you share the command that generated the error? And if your benchmark is public, can you share a link to the repo?

**Comment by tomMoral** [comment] 2023-06-07 03:25
I think the issue is with the `benchopt install` command, when collecting uninstalled solvers. If there is an import error in the `safe_import_context`, it expect to find a `requirements` attribute. If there is none, I would suggest we raise a more comprehensive error :)

@UR4NVS , do you think you could look into  this? this involves changing the line [here](https://github.com/benchopt/benchopt/blob/main/benchopt/utils/dependencies_mixin.py#L102)
to check if the requirements exists and raise an error asking to add a `requirements` attribute in the solver class if not.

**Comment by Badr-MOUFAD** [comment] 2023-07-03 14:06
Should it be closed after the merge of #562?

**Comment by mathurinm** [comment] 2023-07-11 08:42
fixed by #562

**Closed by mathurinm** 2023-07-11 08:42 UTC
