### ISSUE TITLE
BUG fail to run default benchmark (PyPI version)

### ISSUE THREAD

**Issue by gdurif** [benchopt/benchOpt#130] opened 2021-01-12 15:19 UTC
Hi,

On a fresh install (inside a clean python virtual environment) via `pip`, I cannot run any of the standard benchmarks

```bash
$ pip install benchopt
$ git clone https://github.com/benchopt/benchmark_ols
$ benchopt run benchmark_ols 
Traceback (most recent call last):
  File "/xxxx/benchopt/.pyenv/bin/benchopt", line 11, in <module>
    sys.exit(main())
  File "/xxxx/benchopt/.pyenv/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/xxxx/benchopt/.pyenv/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/xxxx/benchopt/.pyenv/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/xxxx/benchopt/.pyenv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/xxxx/benchopt/.pyenv/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/xxxx/benchopt/.pyenv/lib/python3.6/site-packages/benchopt/cli.py", line 80, in run
    validate_dataset_patterns(benchmark, dataset_names)
  File "/xxxx/benchopt/.pyenv/lib/python3.6/site-packages/benchopt/utils/checkers.py", line 35, in validate_dataset_patterns
    datasets = list_benchmark_datasets(benchmark)
  File "/xxxx/benchopt/.pyenv/lib/python3.6/site-packages/benchopt/util.py", line 104, in list_benchmark_datasets
    return _list_benchmark_classes(benchmark_dir, 'Dataset')
  File "/xxxx/benchopt/.pyenv/lib/python3.6/site-packages/benchopt/util.py", line 91, in _list_benchmark_classes
    classes.append(_load_class_from_module(module_filename, class_name))
  File "/xxxx/benchopt/.pyenv/lib/python3.6/site-packages/benchopt/utils/dynamic_modules.py", line 46, in _load_class_from_module
    module = _get_module_from_file(module_filename)
  File "/xxxx/benchopt/.pyenv/lib/python3.6/site-packages/benchopt/utils/dynamic_modules.py", line 22, in _get_module_from_file
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "benchmark_ols/datasets/boston.py", line 1, in <module>
    from benchopt import BaseDataset
ImportError: cannot import name 'BaseDataset'
```

same for `benchmark_lasso`, `benchmark_logreg_l2`, `benchmark_logreg_l1`, `benchmark_nnls`.

Here  are my system info:

```bash
$ python -V
Python 3.6.9
$ uname -a
Linux xxxx 5.4.0-59-generic #65~18.04.1-Ubuntu SMP Mon Dec 14 15:59:40 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
Am I missing something ? Thanks in advance

**Comment by tomMoral** [comment] 2021-01-12 15:38
The issue is that we broke everything and we need to do a new release :)
We need to do proper versionning for the benchmarks but I am ensure of how to do it.
You should be able to run the benchmark with the master branch of `benchopt`.

**Comment by gdurif** [comment] 2021-01-12 16:07
Ok, no problem, thanks.

**Comment by tomMoral** [comment] 2021-11-25 09:22
This one should be fixed, feel free to open a new one if there is still a problem when using the doc instruction.

**Closed by tomMoral** 2021-11-25 09:22 UTC
